version: 0.2

env:
  variables:
    ANDROID_SDK_ROOT: /usr/local/android-sdk
    ANDROID_HOME: /usr/local/android-sdk
    KEYSTORE_PATH: /tmp/todo-release-key.keystore
  parameter-store:
    KEYSTORE_PASSWORD: /todo-app/dev/keystore-password


phases:
  install:
    runtime-versions:
      nodejs: 20
      java: corretto17
    commands:
      - |
        if [ ! -d "$ANDROID_SDK_ROOT/cmdline-tools/latest" ]; then
          echo "Installing Android SDK..."
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O /tmp/cmdline-tools.zip
          mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
          unzip -q /tmp/cmdline-tools.zip -d $ANDROID_SDK_ROOT/cmdline-tools
          mv $ANDROID_SDK_ROOT/cmdline-tools/cmdline-tools $ANDROID_SDK_ROOT/cmdline-tools/latest
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
          yes | sdkmanager --licenses > /dev/null
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0" "cmake;3.22.1" "ndk;26.1.10909125"
        else
          echo "✅ Android SDK restored from cache"
          export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
        fi
      - npm install -g serverless@3.38.0
      - npm install

  pre_build:
    commands:
      - |
        echo "=== Checking if keystore exists in S3 ==="
        if aws s3 ls s3://todo-keystore-bucket/todo-release-key.keystore --region ap-south-1 2>/dev/null; then
          echo "✅ Keystore already exists, downloading..."
          aws s3 cp s3://todo-keystore-bucket/todo-release-key.keystore /tmp/todo-release-key.keystore --region ap-south-1
        else
          echo "❌ Keystore not found, generating new one..."
          keytool -genkeypair -v -storetype PKCS12 \
            -keystore /tmp/todo-release-key.keystore \
            -alias todo-key-alias \
            -keyalg RSA -keysize 2048 -validity 10000 \
            -storepass ${KEYSTORE_PASSWORD} \
            -keypass ${KEYSTORE_PASSWORD} \
            -dname "CN=Hasil, OU=Dev, O=TodoApp, L=City, ST=State, C=IN"
          
          echo "Uploading new keystore to S3..."
          aws s3 cp /tmp/todo-release-key.keystore s3://todo-keystore-bucket/todo-release-key.keystore --region ap-south-1
        fi

  build:
    commands:
      - export ANDROID_HOME=/usr/local/android-sdk
      - export ANDROID_SDK_ROOT=/usr/local/android-sdk
      - export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools
      - export KEY_ALIAS=todo-key-alias
      - export KEY_PASSWORD=${KEYSTORE_PASSWORD}

      - echo "Building APK..."
      - cd android
      - chmod +x ./gradlew
      - ./gradlew assembleRelease --no-daemon 
      - cd ..

      - echo "File Name"
      - find . -name "*.apk" -type f

      - echo "Deploying Lambda..."
      - serverless deploy --stage dev --verbose

artifacts:
  files:
    - android/app/build/outputs/apk/release/app-release.apk
  discard-paths: yes

cache:
  paths:
    - node_modules/**/*       
    - /root/.gradle/**/*        
    - /root/.npm/**/* 
    - /usr/local/android-sdk/**/* 
    - android/app/.cxx/**/*    
    - android/app/build/intermediates/**/* 